name: Release Express App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Actualizado a v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Actualizado a v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6 # Actualizado a v6
        with:
          context: .
          push: true
          # IMPORTANTE: Reemplaza 'tu_usuario' si no usas la variable, 
          # pero es mejor usar la variable secreta para el tag tambi√©n si prefieres.
          tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
